# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh
  setopt no_unset extended_glob

  # Unset all configuration options. This allows you to apply configiguration changes without
  # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
  unset -m 'POWERLEVEL9K_*'

  autoload -Uz is-at-least && is-at-least 5.1 || return

  zmodload zsh/langinfo
  if [[ ${langinfo[CODESET]:-} != (utf|UTF)(-|)8 ]]; then
    local LC_ALL=${${(@M)$(locale -a):#*.(utf|UTF)(-|)8}[1]:-en_US.UTF-8}
  fi

  typeset -g POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
  typeset -g POWERLEVEL9K_MODE='nerdfont-complete'
  typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
  typeset -g POWERLEVEL9K_STATUS_VERBOSE=false
  typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND='022'
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'
  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='white'
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='black'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='black'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='blue'
  # POWERLEVEL9K_FOLDER_ICON="$(print_icon FOLDER_ICON)"
  typeset -g POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true
  typeset -g POWERLEVEL9K_STATUS_VERBOSE=false
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='\uf417'
  # POWERLEVEL9K_K8S_ICON="\u2388"
  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_DEFAULT_NAMESPACE=false
  typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
    '*prod*'    PROD
    '*staging*' STAGING
    '*'         DEFAULT)
  typeset -g POWERLEVEL9K_KUBECONTEXT_PROD_FOREGROUND=black
  typeset -g POWERLEVEL9K_KUBECONTEXT_PROD_BACKGROUND=red
  typeset -g POWERLEVEL9K_KUBECONTEXT_STAGING_BACKGROUND='022'
  typeset -g POWERLEVEL9K_KUBECONTEXT_STAGING_FOREGROUND='white'
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=black
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=green

  typeset -g POWERLEVEL9K_TERRAFORM_CLASSES=(
    '*prod*'    PROD
    '*staging*' STAGING
    '*'         DEFAULT)
  typeset -g POWERLEVEL9K_TERRAFORM_PROD_FOREGROUND="$POWERLEVEL9K_KUBECONTEXT_PROD_FOREGROUND"
  typeset -g POWERLEVEL9K_TERRAFORM_PROD_BACKGROUND="$POWERLEVEL9K_KUBECONTEXT_PROD_BACKGROUND"
  typeset -g POWERLEVEL9K_TERRAFORM_STAGING_BACKGROUND="$POWERLEVEL9K_KUBECONTEXT_STAGING_BACKGROUND"
  typeset -g POWERLEVEL9K_TERRAFORM_STAGING_FOREGROUND="$POWERLEVEL9K_KUBECONTEXT_STAGING_FOREGROUND"
  typeset -g POWERLEVEL9K_TERRAFORM_DEFAULT_FOREGROUND="$POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND"
  typeset -g POWERLEVEL9K_TERRAFORM_DEFAULT_BACKGROUND="$POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND"

  typeset -g POWERLEVEL9K_AWS_CLASSES=(
    '*prod*'    PROD
    '*staging*' STAGING
    '*'         DEFAULT)
  typeset -g POWERLEVEL9K_AWS_PROD_FOREGROUND="$POWERLEVEL9K_KUBECONTEXT_PROD_FOREGROUND"
  typeset -g POWERLEVEL9K_AWS_PROD_BACKGROUND="$POWERLEVEL9K_KUBECONTEXT_PROD_BACKGROUND"
  typeset -g POWERLEVEL9K_AWS_STAGING_BACKGROUND="$POWERLEVEL9K_KUBECONTEXT_STAGING_BACKGROUND"
  typeset -g POWERLEVEL9K_AWS_STAGING_FOREGROUND="$POWERLEVEL9K_KUBECONTEXT_STAGING_FOREGROUND"
  typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND="$POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND"
  typeset -g POWERLEVEL9K_AWS_DEFAULT_BACKGROUND="$POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND"
  # POWERLEVEL9K_VCS_UNTRACKED_ICON="$(print_icon VCS_UNSTAGED_ICON)"
  # POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON="$(print_icon VCS_INCOMING_CHANGES_ICON)"
  # POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON="$(print_icon VCS_OUTGOING_CHANGES_ICON)"
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
  typeset -g POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX=""
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status root_indicator dir dir_writable_joined)
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs background_jobs_joined terraform aws kubecontext) # nvm rbenv)

  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  (( ! $+functions[p10k] )) || p10k reload
}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'